const charData = [
  { id: 1, name: "Arlan" },
  { id: 2, name: "Asta" },
  { id: 3, name: "Bailu" },
  { id: 4, name: "Blade" },
  { id: 5, name: "Bronya" },
  { id: 6, name: "Clara" },
  { id: 7, name: "Dan Heng" },
  { id: 8, name: "Fu Xuan" },
  { id: 9, name: "Gepard" },
  { id: 10, name: "Himeko" },
  { id: 11, name: "Hook" },
  { id: 12, name: "Herta" },
  { id: 13, name: "Inbibitor Lunae - Dan Heng" },
  { id: 14, name: "Jing Yuan" },
  { id: 15, name: "Kafka" },
  { id: 16, name: "Luka" },
  { id: 17, name: "Luocha" },
  {
    id: 18,
    name: "Lynx",
  },
  { id: 19, name: "March 7th" },
  { id: 20, name: "Trailblazer" },
  { id: 21, name: "Natasha" },
  { id: 22, name: "Pela" },
  { id: 23, name: "Qingque" },
  { id: 24, name: "Sampo" },
  { id: 25, name: "Seele" },
  { id: 26, name: "Serval" },
  { id: 27, name: "Silver Wolf" },
  { id: 28, name: "Sushang" },
  { id: 29, name: "Tingyun" },
  { id: 30, name: "Welt" },
  { id: 31, name: "Yanqing" },
  { id: 32, name: "Yukong" },
  // { id: 33, name: "Placeholder" },
  // { id: 34, name: "Placeholder" },
  // { id: 35, name: "Placeholder" },
  // { id: 36, name: "Placeholder" },
];
export default charData;
